
exception NotFoundError {
	1:string message;
	2:list<list<i16>> x;
}

service ExceptionTest {
	void check() throws (1:NotFoundError)
}

